# Generated by Django 4.0.3 on 2024-07-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser1_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser1',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser1',
            name='email',
            field=models.EmailField(max_length=20, unique=True, verbose_name='Email Address'),
        ),
    ]
